name: stomp
author: Tom Yeh <tomyeh@rikulo.org>
version: 0.5.5
homepage: https://github.com/rikulo/stomp
description: Dart STOMP client for easy messaging interoperability.
documentation: http://api.rikulo.org/stomp/latest
environment:
  sdk: '>=0.8.7'
dependencies:
  quiver: any
  unittest: any
